remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Omri Bar-Oz
description: Art trader by day. Art enjoyer by night. Sophisticated algorithm developer, striving to achieve fairness and love in the world.