theme: jekyll-theme-merlot
title: Omri Bar-Oz
description: Art trader by day. Art enjoyer by night. Sophisticated algorithm writer, striving to improve the world by understanding what is legitimate and what is not.